# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lullrich/Dokumente/Studium/4_Semester/Chip_Design/Project/VGA_Controller/generate/spaceinvader/spaceinvader/spaceinvader.xci
# IP: The module: 'spaceinvader' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lullrich/Dokumente/Studium/4_Semester/Chip_Design/Project/VGA_Controller/generate/spaceinvader/spaceinvader/spaceinvader_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spaceinvader'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/lullrich/Dokumente/Studium/4_Semester/Chip_Design/Project/VGA_Controller/generate/spaceinvader/spaceinvader/spaceinvader.xci
# IP: The module: 'spaceinvader' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lullrich/Dokumente/Studium/4_Semester/Chip_Design/Project/VGA_Controller/generate/spaceinvader/spaceinvader/spaceinvader_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'spaceinvader'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
